name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install required dependencies for Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff1 \
            libvpx5 \
            libevent-2.1-7 \
            libopus0 \
            libgstapp-1.0-0 \
            libgstpbutils-1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer-plugins-good1.0-0 \
            libgstreamer1.0-0 \
            libharfbuzz-icu0 \
            libhyphen0 \
            libflite1 \
            libgles2-mesa \
            libx264-155

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ./src

      - name: Run lint
        run: npm run test-lint
        working-directory: ./src

      - name: Run unit tests
        run: npm run test-unit
        working-directory: ./src

      - name: Run integration tests
        run: npm run test-integration
        working-directory: ./src

      - name: Run end-to-end tests
        run: npm run test-e2e
        working-directory: ./src

      - name: Upload code coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: src/coverage

  build-artifacts:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./src

      - name: Build application
        run: npm run build
        working-directory: ./src

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: src/build
