name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Update Node.js version to 16

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run test-lint

      - name: Run unit tests
        run: npm run test-unit

      - name: Run integration tests
        run: npm run test-integration

      - name: Run end-to-end tests
        run: npm run test-e2e

      - name: Generate build artifact
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Upload build artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-reports
          path: coverage
